services:
  game-server-0:
    container_name: tag-server-0
    build: ./tag
    ports:
      - "5000:5000"
  trainer-0:
    container_name: tag-trainer-0
    build: ./trainer
    environment:
      - AWS_BATCH_JOB_MAIN_NODE_INDEX=0
      - AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS=trainer-0
      - AWS_BATCH_JOB_NODE_INDEX=0
      - AWS_BATCH_JOB_NUM_NODES=5
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
  game-server-1:
    container_name: tag-server-1
    build: ./tag
    ports:
      - "5001:5000"
  trainer-1:
    container_name: tag-trainer-1
    build: ./trainer
    environment:
      - AWS_BATCH_JOB_MAIN_NODE_INDEX=0
      - AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS=trainer-0
      - AWS_BATCH_JOB_NODE_INDEX=1
      - AWS_BATCH_JOB_NUM_NODES=5

  game-server-2:
    container_name: tag-server-2
    build: ./tag
  trainer-2:
    container_name: tag-trainer-2
    build: ./trainer
    environment:
      - AWS_BATCH_JOB_MAIN_NODE_INDEX=0
      - AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS=trainer-0
      - AWS_BATCH_JOB_NODE_INDEX=2
      - AWS_BATCH_JOB_NUM_NODES=5

  game-server-3:
    container_name: tag-server-3
    build: ./tag
  trainer-3:
    container_name: tag-trainer-3
    build: ./trainer
    environment:
      - AWS_BATCH_JOB_MAIN_NODE_INDEX=0
      - AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS=trainer-0
      - AWS_BATCH_JOB_NODE_INDEX=3
      - AWS_BATCH_JOB_NUM_NODES=5

  game-server-4:
    container_name: tag-server-4
    build: ./tag
  trainer-4:
    container_name: tag-trainer-4
    build: ./trainer
    environment:
      - AWS_BATCH_JOB_MAIN_NODE_INDEX=0
      - AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS=trainer-0
      - AWS_BATCH_JOB_NODE_INDEX=4
      - AWS_BATCH_JOB_NUM_NODES=5
  
  tensorboard-server:
    container_name: tensorboard-server
    build: ./tensorboard
    ports:
      - "6006:6006"
    volumes:
      - type: bind
        source: ./logs
        target: /logs
  